### PR TITLE
feat: Added override for Sentry CLI URL

### PR DESCRIPTION
**Pull request by Swatinem**
This is useful for self-hosted users, as well as for local testing ;-)

### CODE REVIEW

**Comment by vaind** [comment]
Why do we need to configure a different URL than the one in the main options tab?
image

**Comment by Swatinem** [comment]
The new setting is specific to how sentry-cli is invoked, as in: where to upload the debug files.

**Comment by vaind** [comment]
> The new setting is specific to how sentry-cli is invoked, as in: where to upload the debug files.

Got it, but why would we want/need it to be different than the DSN? When would it be necessary to have symbol upload to a different server than the one where the events will be uploaded?

**Comment by Swatinem** [comment]
> to a different server than the one where the events will be uploaded?

Well you wouldn’t. That’s why the setting is needed, otherwise sentry-cli would always try to upload to the SaaS instance.

Or are you rather suggesting to parse the DSN and extract the url from there?

**Comment by vaind** [comment]
> That’s why the setting is needed, otherwise sentry-cli would always try to upload to the SaaS instance.

sorry, my bad. I've assumed it already uses the DSN.

> Or are you rather suggesting to parse the DSN and extract the url from there?

IMO we should do exactly that. Otherwise, it wouldn't work with self-hosted instances, which I guess is a common use case.

**Review by bitsandfoxes — APPROVED** [review]

**Pull request merged**
