### PR TITLE
Change access modifier to `private` for stack trace mode option setter

### LINKED ISSUE #1783: WebGL exception during IL2CPP processing
Reported on [Discord](https://discord.com/channels/621778831602221064/1246915557731860511/1278277335615012935)

Triggering an exception causes the IL2CPP backend to throw one of its own.

Image
Image

We might need to disable the automatic integration of the IL2CPP exception processor for WebGL.

### PR DESCRIPTION
**Pull request by tustanivsky**
This PR should prevent users from accidentally enabling `Enhanced` stack trace mode via the `SentryUnityOptions` parent class property. Enhanced mode is not supported in IL2CPP builds (see #1033 for more details) and thus could cause crashes like in #1783.

Closes #1783

### CODE REVIEW

**Review by bruno-garcia — CHANGES_REQUESTED** [review]
Looks like the whole property was `private` though (getter and setter). We're making the getter public but the setter private. Is this helping somehow?

**Comment by bruno-garcia** [comment]
> 
What we wanted to achieve was take away the footgun for users to switch mode and break their game by hiding the property. But it's still accessible via the base class. With this we're giving the "no-footgun!" attempt a second chance.


As per my comment, isnt' the whole thing `private` and now we're making half private? If not, I might misundersatnd the code.

**Comment by bitsandfoxes** [comment]
> As per my comment, isnt' the whole thing private and now we're making half private? If not, I might misundersatnd the code.

Making the property private on the child only hides it on the child. Accessing the property i.e. in the configure callback falls back directly to the `SentryOptions`. 

Screenshot 2024-10-07 at 16 23 37

Keeping the property `public` but overwriting the accessor on the setter allows us to put a hurdle in front of the footgun.

Screenshot 2024-10-07 at 16 22 48

**Review by bitsandfoxes — APPROVED** [review]
Thanks for finding this!

**Comment by bruno-garcia** [comment]
Thank you for clarifying that

**Pull request merged**
