### PR TITLE
chore: Bump to 2020.3.28 & 2021.2.11

### PR DESCRIPTION
**Pull request by bitsandfoxes**
Context: Trying to stay current to catch any issues like https://github.com/getsentry/sentry-unity/issues/550 that come up with new versions as early as possible.

#skip-changelog

### CODE REVIEW

**Comment by vaind** [comment]
FYI: I've pushed the latest unity-version docker images now: https://github.com/getsentry/unity-docker/pkgs/container/unity-docker/versions

**Comment by bruno-garcia** [comment]
> FYI: I've pushed the latest unity-version docker images now: [getsentry/unity-docker/pkgs/container/unity-docker/versions](https://github.com/getsentry/unity-docker/pkgs/container/unity-docker/versions)

Does it mean we can merge this PR now and they'll be aligned?

**Comment by vaind** [comment]
> > FYI: I've pushed the latest unity-version docker images now: [getsentry/unity-docker/pkgs/container/unity-docker/versions](https://github.com/getsentry/unity-docker/pkgs/container/unity-docker/versions)
> 
> Does it mean we can merge this PR now and they'll be aligned?

not really, there are merge conflicts that need to be resolved.

**Comment by bruno-garcia** [comment]
> Also, have you seen [getsentry/unity-docker#2](https://github.com/getsentry/unity-docker/pull/2) @bruno-garcia ? That changes the actions to always push the currently available latest version. There's 2021.2.12 available now

Makes sense. I left a comment on your PR about auto updating though. In general the strategy is really excellent and will make our lifes much easier

**Pull request closed without merging**
