### PR TITLE
Update SentrySdk.cs

### PR DESCRIPTION
**Pull request by AMiNMirzapoor**

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@AMiNMirzapoor could you describe a bit this scenario?
Are you seeing exceptions that don't have the `:` delimiter? And if so, what part is missing, the type or the message?

**Comment by AMiNMirzapoor** [comment]
Yes, I saw exceptions that didn't have the : delimiter.
Sorry, I don't remember what part was missing, and couldn't reproduce it!

**Comment by mrobaczyk** [comment]
`
        var excValue = "";
        if ((exc.Length >= 2) && (exc[1].Length >= 2))
        {
            excValue = exc[1].Substring(1); // strip the space
        }
`

This is what I applied in my application.

**Comment by bruno-garcia** [comment]
Sorry this got lost. The code made through now:
https://github.com/getsentry/sentry-unity-lite/commit/409debcf5928870395e7c8c6d81e26e98f3d0941

There are some announcements here: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222

**Pull request closed without merging**
