### PR TITLE
Strip zeroes for ill2cpp builds

### LINKED ISSUE #103: IL2CPP doesn't have file name:
Don't add stacktrace "filename" if it's <0000>.

### PR DESCRIPTION
**Pull request by semuserable**
closes #103

### CODE REVIEW

**Comment by semuserable** [comment]
@bruno-garcia license again..

**Review by bruno-garcia — COMMENTED** [review]
Looks good but needs some tests

**Comment by semuserable** [comment]
@bruno-garcia test added

**Comment by semuserable** [comment]
seems there is a problem with nuget on build machine

**Comment by Tyrrrz** [comment]
@semuserable looks like an issue in GitHub Actions infrastructure, I see it throughout other projects as well.
https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782

**Comment by Tyrrrz** [comment]
@semuserable rebase on latest `main` please

**Review by bruno-garcia — APPROVED** [review]
:shipit:

**Pull request merged**
