### PR TITLE
bump dotnet 3.3.4

### PR DESCRIPTION
**Pull request by bruno-garcia**
Superceed #126

### CODE REVIEW

**Review by semuserable — APPROVED** [review]

**Comment by bruno-garcia** [comment]
This was rebased from main and still fails. Not sure yet what's going on, need investigating

**Comment by semuserable** [comment]
After previous problems with `il2cpp`, have you checked it on `il2cpp` before merging? :)

**Comment by bruno-garcia** [comment]
@semuserable IL2WHAT?

**Comment by bruno-garcia** [comment]
Sorry, I didn't. But the fixes there are trivial.
I hope we land the IL2CPP test soon to help with these checks

**Pull request merged**
