### PR TITLE
Force 'Auto' from sentry window

### PR DESCRIPTION
**Pull request by semuserable**
closes https://github.com/getsentry/sentry-unity/issues/217

I decided to force `Auto` if you configure from sentry window. We can differentiate between scripting backends with the following code

```csharp
PlayerSettings.GetScriptingBackend(EditorUserBuildSettings.selectedBuildTargetGroup) == ScriptingImplementation.IL2CPP
```

but it's available only in `Unity.Editor.dll`. We could do that logic not on options level, but on window level itself.

Which path should we take?

**PS**. Please notice, I didn't include tests as I'm trying to understand which approach we take.

### CODE REVIEW

**Comment by semuserable** [comment]
updated

cc @bruno-garcia @bitsandfoxes

**Review by bruno-garcia — COMMENTED** [review]
We can merge this but I used the programatic approach and turns out it doesn't default to `Auto` there so it ends up breaking IL2CPP.

So basically what we need is to always set `base.CompressionLevel = NoCompression` through the `SetDefaults` method so that's done regardless of how `SentryUnityOptions` is created

**Comment by semuserable** [comment]
Interesting. Ok, will move it into defaults then.

**Comment by semuserable** [comment]
Changed to `NoCompression` and moved into defaults.

cc @bruno-garcia

**Review by bitsandfoxes — APPROVED** [review]

**Pull request merged**
