### PR TITLE
Tag whether event was created in the UI thread

### LINKED ISSUE #62: Tag whether event was created in the UI thread
We should add a tag that indicates whether the event was raised from the UI thread or not

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes  #62

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
PR looks ok for me.

@bruno-garcia , do you know if it's possible to add the main thread info next to the mechanism? picture for reference
image

So we could have a new item called [main_thread] or [main thread] and set True/False.

Event for reference: https://sentry.io/organizations/sentry-sdks/issues/2866761831/?project=5428557&query=&statsPeriod=90d

**Comment by SimonCropp** [comment]
are the broken builds expected?

**Comment by bitsandfoxes** [comment]
> are the broken builds expected?

No, not really. Main is breaking too without apparent changes.

**Comment by bruno-garcia** [comment]
> PR looks ok for me.
> 
> 
> 
> @bruno-garcia , do you know if it's possible to add the main thread info next to the mechanism? picture for reference
> 
> image
> 
> 
> 
> So we could have a new item called [main_thread] or [main thread] and set True/False.
> 
> 
> 
> Event for reference: https://sentry.io/organizations/sentry-sdks/issues/2866761831/?project=5428557&query=&statsPeriod=90d

Yeah this is something that makes sense to align across all sdks. @philipphofmann I believe had a DACI about this. Or possibly @marandaneto who is away until beginning of January in vacation. Let's figure this out before we release this.

**Pull request merged**
