### PR TITLE
feat: Marking Unity exceptions as unhandled by default

### PR DESCRIPTION
**Pull request by bitsandfoxes**
Resolving https://github.com/getsentry/sentry-unity/issues/532

### CODE REVIEW

**Comment by SimonCropp** [comment]
can a test be added that actually throws an exception and assert that is it captured with the correct mechanism?

**Review by bruno-garcia — APPROVED** [review]
Great! This will need some documentation though.

**Comment by bruno-garcia** [comment]
> Messages
> 📖	Do not forget to update [Sentry-docs](https://github.com/getsentry/sentry-docs) with your feature once the pull request gets approved.
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [f3386c7](https://github.com/getsentry/sentry-unity/commit/f3386c7ae76d239aa6d9b6f6dd45eee5fe90c1b4)

yes please

**Comment by bitsandfoxes** [comment]
Waiting to be merged on the next release: https://github.com/getsentry/sentry-docs/pull/4677

**Pull request merged**
