### PR TITLE
Add Latest Android Simulator

### LINKED ISSUE #704: Runs smoke tests on Android newer API levels
The latest API we test against is 30 (which found a bug in either Unity or our SDK+Unity in #686)
We need to test API 32. API 31 had minimum changes so we can keep it out.

Additionally, a `latest` build that run if a API level is available that we haven't hard coded yet (e.g: 32 comes up).

### PR DESCRIPTION
**Pull request by lucas-zimerman**
This PR includes the latest Android version on the smoke test and also updates the action `reactivecircus/android-emulator-runner` (CI looks more organized on the Smoke test)

#skip-changelog

Close #704

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
@bruno-garcia  we need to add x86_x64 to the test app in order to support versions newer than 31

**Comment by bruno-garcia** [comment]
> @bruno-garcia we need to add x86_x64 to the test app in order to support versions newer than 31

IIRC @vaind had to remove it. Or rather didn't Ivan add it so things speed up?

Sorry not sure where we stand anymore

**Comment by vaind** [comment]
> IIRC @vaind had to remove it. Or rather didn't Ivan add it so things speed up?

Actually neither of those, I've removed the arm build because we didn't need it. We didn't even have x86_64 and would need to add it to the project config

**Comment by lucas-zimerman** [comment]
@vaind  @bruno-garcia  any ideas why Unity doesn't initialize on the latest Android?
https://github.com/getsentry/sentry-unity/runs/6291296258?check_suite_focus=true

I noticed that Sentry Android SDK always initializes on all the runs but Unity itself sometimes doesn't initialize  on the latest version.
out of curiosity I disabled the Native SDK on the latest commit and since then Unity always initializes on the latest version.

**Comment by vaind** [comment]
> @vaind @bruno-garcia any ideas why Unity doesn't initialize on the latest Android? https://github.com/getsentry/sentry-unity/runs/6291296258?check_suite_focus=true

Anything to do with the "System UI not responding" that the emulator is stuck on?
screen

Some SO answer seems to suggest enabling hardware accelerated graphics: https://stackoverflow.com/questions/63371056/the-system-ui-isnt-responding-in-android-emulator-flutter


P.S. It may be a good idea to squash+rebase or just merge main in - there were some conflicting changes about two weeks ago.

**Comment by lucas-zimerman** [comment]
Closing due to age, will rework it on another PR.

**Pull request closed without merging**
