### PR TITLE
fix: remove ios embed framework build phase duplication (#1558)

### PR DESCRIPTION
**Pull request by munkiki7**
image

The linking phase is still added multiple times, but I could not find a way to check if it is already added.
But this does not break the build.

### CODE REVIEW

**Comment by bitsandfoxes** [comment]
> The linking phase is still added multiple times, but I could not find a way to check if it is already added.

Can't we just check for one of the things we do (i.e. adding the framework) and bail early instead of linking it twice?

**Comment by munkiki7** [comment]
> > The linking phase is still added multiple times, but I could not find a way to check if it is already added.
> 
> Can't we just check for one of the things we do (i.e. adding the framework) and bail early instead of linking it twice?

This is a completely separate point, so, for example, if the user builds, then opens the XCode project, and deletes the link task, and builds again, it won't be added. This is a low-probability case, and a clean build will fix it.

So, do you want me to leave it as is, or do only one check for framework and linking as you have proposed?

**Comment by bitsandfoxes** [comment]
> This is a completely separate point, so, for example, if the user builds, then opens the XCode project, and deletes the link task, and builds again, it won't be added. This is a low-probability case, and a clean build will fix it.

I think this is very much self-inflicted then and we're good.

**Review by bitsandfoxes — APPROVED** [review]
Thanks!

**Pull request merged**
